defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
company_name: "Organa"
google_analytics_tracker_code: "UA-136781112-2"
title: Organa DNA
description: How Organa works as a organisation, aka the Organa DNA!
google_analytics: UA-7074695-4
show_downloads: true
theme: jekyll-theme-cayman
repository: organa-dna/dna
github: [metadata]