defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
company_name: "Product Space"
google_analytics_tracker_code: "UA-7074695-4"
title: Product Space DNA
description: How Product Space works as a organisation, aka the Product Space DNA!x
google_analytics: UA-7074695-4
show_downloads: true
theme: jekyll-theme-cayman